server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: explore-rx-spring
  data:
    mongodb:
      authentication-database: admin
#      username:
#      password:
      host: localhost
      database: school
      port: 27017